"""SAVE FORMAT v2 tests — canonical round-trip, taxonomy, fuzz, migration.

Five layers, mirroring the module's published guarantees
(``docs/persistence.md``):

1. **Canonical determinism** — one state, one byte-identical string,
   regardless of dict insertion order; the empty-state literal and the
   doc's worked example are pinned (md-parity: edit either side alone
   and the suite goes red).
2. **Exact round-trip** — ``load(dump(s)) == s`` over seeded random
   rosters (reusing the property suite's generators) and astronomically
   large integers; ``dump(load(t)) == t`` for canonical ``t`` and for
   any accepted non-canonical spelling (idempotent canonicalization).
3. **Error taxonomy** — every documented failure raises its distinct
   :class:`SaveError` subclass; encode-side validation refuses what the
   loader would refuse.
4. **Tamper/fuzz** — seeded corruptions of canonical saves either raise
   a documented subclass or load into a valid GameState that itself
   round-trips; never any other outcome.
5. **Migration** — the registry carries its FIRST REAL migration
   (v1→v2: the achievements slice added ``milestones``); v1 documents
   load through it into first-class v2 states, and a synthetic v0->v1
   migration registered in-test still proves multi-step dispatch;
   misbehaving migrations fail loud.

Randomness is stdlib-only with fixed seeds (the repo's no-hypothesis
convention) so CI runs are byte-for-byte reproducible.
"""

import dataclasses
import json
import re
import string
from pathlib import Path
from random import Random

import pytest

from idle_engine import GameState, load_theme
from idle_engine import persistence
from idle_engine.achievements import award_milestones
from idle_engine.engine import apply_offline_progress, tick
from idle_engine.persistence import (
    STATE_VERSION,
    FieldSetError,
    FieldTypeError,
    InvalidStateError,
    MalformedSaveError,
    NegativeValueError,
    SaveError,
    UnknownVersionError,
    dump_state,
    load_state,
)
from idle_engine.prestige import apply_prestige, prestige_eligible
from idle_engine.upgrades import purchase_upgrade, upgrade_cost
from test_properties import _random_roster  # the property suite's seeded generators

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "persistence.md"

CANONICAL_EMPTY = (
    '{"balances":{},"last_seen":0,"lifetime":{},"milestones":{},"owned":{},'
    '"prestige":{},"state_version":2,"upgrades":{}}'
)

CANONICAL_V1_EMPTY = (
    '{"balances":{},"last_seen":0,"lifetime":{},"owned":{},'
    '"prestige":{},"state_version":1,"upgrades":{}}'
)

DOCUMENTED_ERRORS = (
    MalformedSaveError,
    UnknownVersionError,
    FieldSetError,
    FieldTypeError,
    NegativeValueError,
)


def _valid_doc(**overrides) -> dict:
    """A well-formed v2 document, tweakable per test."""
    doc = {
        "state_version": 2,
        "balances": {"cur-a": 42},
        "owned": {"gen-a": 3},
        "last_seen": 1_700_000_000,
        "upgrades": {"up-a": 2},
        "lifetime": {"cur-a": 999},
        "prestige": {"meta": 1},
        "milestones": {"owned-1": 1},
    }
    doc.update(overrides)
    return doc


def _valid_v1_doc(**overrides) -> dict:
    """A well-formed LEGACY v1 document (no milestones field)."""
    doc = _valid_doc(state_version=1)
    del doc["milestones"]
    doc.update(overrides)
    return doc


# --- 1. canonical determinism ---------------------------------------------------


def test_empty_state_canonical_literal_is_pinned():
    assert dump_state(GameState()) == CANONICAL_EMPTY


def test_dump_is_deterministic_and_insertion_order_free():
    a = GameState(balances={"x": 1, "y": 2}, owned={"g": 1}, lifetime={"y": 4, "x": 3})
    b = GameState(balances={"y": 2, "x": 1}, owned={"g": 1}, lifetime={"x": 3, "y": 4})
    assert a == b  # dict equality ignores order...
    assert dump_state(a) == dump_state(b) == dump_state(a)  # ...and so does the dump


def test_dump_has_no_whitespace_floats_or_non_ascii():
    state = GameState(balances={"café": 7}, last_seen=5)
    text = dump_state(state)
    assert " " not in text and "\n" not in text
    assert "." not in text  # ints only, so no float ever prints a dot
    assert text.isascii()
    assert load_state(text) == state  # escapes round-trip


@pytest.mark.parametrize("seed", range(20))
def test_same_seed_same_bytes(seed):
    state = _random_roster(Random(11_000 + seed))[0]
    again = _random_roster(Random(11_000 + seed))[0]
    assert dump_state(state) == dump_state(again)


def test_doc_worked_example_dumps_exactly():
    """md-parity: the doc's canonical example is generated by the real encoder."""
    text = DOC_PATH.read_text(encoding="utf-8")
    blocks = re.findall(r"```json\n(.*?)\n```", text, re.DOTALL)
    assert blocks, "docs/persistence.md must carry a ```json worked example"
    empty = dump_state(GameState())
    example = dump_state(
        GameState(
            balances={"cur-a": 42},
            owned={"gen-a": 3},
            last_seen=1_700_000_000,
            upgrades={"up-a": 2},
            lifetime={"cur-a": 999},
            prestige={"meta": 1},
            milestones={"owned-1": 1},
        )
    )
    # Each documented block is byte-identical to a real dump (strip the
    # doc's display newlines: the examples are single-line literals).
    literals = [block.strip() for block in blocks]
    assert empty in literals and example in literals, (
        "doc examples drifted from the real encoder", literals, [empty, example]
    )


# --- 2. exact round-trip ---------------------------------------------------------


@pytest.mark.parametrize("seed", range(30))
def test_round_trip_is_exact_over_random_states(seed):
    state = _random_roster(Random(12_000 + seed))[0]
    assert load_state(dump_state(state)) == state


def test_round_trip_preserves_explicit_zero_entries():
    state = GameState(balances={"a": 0}, owned={"g": 0})
    loaded = load_state(dump_state(state))
    assert loaded == state and loaded.balances == {"a": 0}


def test_round_trip_at_astronomical_scale():
    state = GameState(
        balances={"a": 10**3000}, lifetime={"a": 10**3000 + 1}, last_seen=2**63
    )
    assert load_state(dump_state(state)) == state


def test_dump_load_is_idempotent_on_canonical_text():
    for seed in range(10):
        canonical = dump_state(_random_roster(Random(13_000 + seed))[0])
        assert dump_state(load_state(canonical)) == canonical


def test_non_canonical_spellings_canonicalize():
    doc = _valid_doc()
    sprawling = json.dumps(doc, indent=2)  # whitespace + insertion order
    canonical = dump_state(load_state(sprawling))
    assert canonical == json.dumps(doc, sort_keys=True, separators=(",", ":"))
    assert dump_state(load_state(canonical)) == canonical


# --- 3. error taxonomy -----------------------------------------------------------


def test_taxonomy_classes_are_distinct_saveerror_subclasses():
    classes = (InvalidStateError, *DOCUMENTED_ERRORS)
    assert all(issubclass(cls, SaveError) for cls in classes)
    assert issubclass(SaveError, ValueError)
    for cls in classes:
        for other in classes:
            if cls is not other:
                assert not issubclass(cls, other)


@pytest.mark.parametrize(
    "text,error",
    [
        (b'{"state_version":1}', MalformedSaveError),  # not a str at all
        ("", MalformedSaveError),
        ("not json", MalformedSaveError),
        ('{"state_version":1', MalformedSaveError),  # truncated
        ("[]", MalformedSaveError),
        ('"a string"', MalformedSaveError),
        ("42", MalformedSaveError),
        ("NaN", MalformedSaveError),  # non-JSON constant, hook-rejected
        ('{"state_version":Infinity}', MalformedSaveError),
        ("{}", FieldSetError),  # no state_version
        ('{"state_version":"1"}', FieldTypeError),
        ('{"state_version":true}', FieldTypeError),
        ('{"state_version":1.0}', FieldTypeError),
        ('{"state_version":2}', FieldSetError),  # current version, fields missing
        ('{"state_version":1}', FieldSetError),  # migrates, then fields missing
        ('{"state_version":3}', UnknownVersionError),  # from the future
        ('{"state_version":0}', UnknownVersionError),  # no migration registered
        ('{"state_version":-3}', UnknownVersionError),
    ],
)
def test_shape_and_version_errors(text, error):
    with pytest.raises(error):
        load_state(text)


def _dump_doc(doc: dict) -> str:
    return json.dumps(doc, sort_keys=True, separators=(",", ":"))


def test_missing_and_unknown_fields_are_field_set_errors():
    missing = _valid_doc()
    del missing["owned"]
    with pytest.raises(FieldSetError, match="owned"):
        load_state(_dump_doc(missing))
    extra = _valid_doc(surplus={"x": 1})
    with pytest.raises(FieldSetError, match="surplus"):
        load_state(_dump_doc(extra))
    both = _valid_doc(surplus=1)
    del both["prestige"]
    with pytest.raises(FieldSetError, match="prestige.*surplus|surplus.*prestige"):
        load_state(_dump_doc(both))


@pytest.mark.parametrize(
    "overrides",
    [
        {"balances": [1, 2]},  # mapping field not an object
        {"balances": 7},
        {"balances": {"a": 1.0}},  # float count — even an integral one
        {"balances": {"a": True}},  # bool is not a count
        {"balances": {"a": "5"}},
        {"balances": {"a": None}},
        {"owned": {"g": [1]}},
        {"milestones": {"m": 1.0}},
        {"milestones": [1]},
        {"last_seen": "0"},
        {"last_seen": 1.5},
        {"last_seen": False},
        {"last_seen": None},
    ],
)
def test_wrong_types_are_field_type_errors(overrides):
    with pytest.raises(FieldTypeError):
        load_state(_dump_doc(_valid_doc(**overrides)))


@pytest.mark.parametrize(
    "overrides",
    [
        {"balances": {"a": -1}},
        {"upgrades": {"u": -10**40}},
        {"milestones": {"m": -1}},
        {"last_seen": -1},
    ],
)
def test_negative_quantities_are_negative_value_errors(overrides):
    with pytest.raises(NegativeValueError):
        load_state(_dump_doc(_valid_doc(**overrides)))


def test_dump_refuses_what_load_would_refuse():
    with pytest.raises(InvalidStateError):
        dump_state({"balances": {}})  # not a GameState
    with pytest.raises(InvalidStateError):
        dump_state(GameState(balances={"a": -1}))
    with pytest.raises(InvalidStateError):
        dump_state(GameState(balances={"a": 1.0}))
    with pytest.raises(InvalidStateError):
        dump_state(GameState(owned={"g": True}))
    with pytest.raises(InvalidStateError):
        dump_state(GameState(lifetime={3: 1}))  # non-string id
    with pytest.raises(InvalidStateError):
        dump_state(GameState(milestones={"m": -1}))
    with pytest.raises(InvalidStateError):
        dump_state(GameState(last_seen=-5))


# --- 4. tamper / fuzz ------------------------------------------------------------

_FUZZ_CHARSET = string.ascii_letters + string.digits + '{}[]":,.-+eE \n'
_FUZZ_TRIALS = 2_000


def _corrupt(rng: Random, text: str) -> str:
    kind = rng.random()
    pos = rng.randrange(len(text))
    if kind < 0.70:  # substitution
        replacement = rng.choice(_FUZZ_CHARSET)
        while replacement == text[pos]:
            replacement = rng.choice(_FUZZ_CHARSET)
        return text[:pos] + replacement + text[pos + 1 :]
    if kind < 0.85:  # deletion
        return text[:pos] + text[pos + 1 :]
    return text[:pos] + rng.choice(_FUZZ_CHARSET) + text[pos:]  # insertion


def test_char_fuzz_every_outcome_is_documented():
    """Seeded character corruption: a documented error, or a valid state.

    There is deliberately no checksum in the save format (saves are not
    typed by hand; integrity is the storage backend's job — see
    docs/persistence.md § Scope), so a digit-level corruption CAN load
    as a different valid state. The published invariant is exactly:
    every accepted text yields a GameState that itself round-trips
    exactly; every rejected text raises a documented SaveError subclass;
    nothing else — no other exception type — can happen.
    """
    rng = Random(0x5AFE)
    outcomes = {"error": 0, "loaded": 0, "loaded_equal": 0}
    error_classes = set()
    for trial in range(_FUZZ_TRIALS):
        state = _random_roster(rng)[0]
        text = dump_state(state)
        corrupted = _corrupt(rng, text)
        if corrupted == text:
            continue
        try:
            loaded = load_state(corrupted)
        except SaveError as exc:
            outcomes["error"] += 1
            error_classes.add(type(exc))
            assert isinstance(exc, DOCUMENTED_ERRORS), type(exc)
        else:
            assert isinstance(loaded, GameState)
            recanon = dump_state(loaded)
            assert load_state(recanon) == loaded  # accepted -> round-trips
            outcomes["loaded"] += 1
            if loaded == state:
                outcomes["loaded_equal"] += 1
    assert outcomes["error"] > 0 and outcomes["loaded"] > 0, outcomes
    # The loud path must dominate: most corruptions break JSON or types.
    assert outcomes["error"] > _FUZZ_TRIALS // 2, outcomes


def test_structured_tamper_maps_to_exact_classes():
    """Document-level tampering hits the SPECIFIC documented class."""
    rng = Random(0xD0C5)
    mutations = (
        ("drop_field", FieldSetError),
        ("add_field", FieldSetError),
        ("rename_field", FieldSetError),
        ("floatify", FieldTypeError),
        ("boolify", FieldTypeError),
        ("stringify", FieldTypeError),
        ("negate", NegativeValueError),
        ("future_version", UnknownVersionError),
        ("array_top", MalformedSaveError),
    )
    fields = (
        "balances",
        "owned",
        "last_seen",
        "upgrades",
        "lifetime",
        "prestige",
        "milestones",
    )
    for trial in range(300):
        state = _random_roster(rng)[0]
        # Guarantee at least one positive entry so negate/floatify can bite.
        state = dataclasses.replace(state, balances={**state.balances, "cur0": 7})
        doc = json.loads(dump_state(state))
        name, expected = mutations[trial % len(mutations)]
        if name == "drop_field":
            del doc[rng.choice(fields)]
        elif name == "add_field":
            doc[f"field{rng.randrange(10)}"] = 0
        elif name == "rename_field":
            picked = rng.choice(fields)
            doc[picked.upper()] = doc.pop(picked)
        elif name == "floatify":
            doc["balances"]["cur0"] = float(doc["balances"]["cur0"])
        elif name == "boolify":
            doc["last_seen"] = True
        elif name == "stringify":
            doc["balances"]["cur0"] = str(doc["balances"]["cur0"])
        elif name == "negate":
            doc["balances"]["cur0"] = -doc["balances"]["cur0"]
        elif name == "future_version":
            doc["state_version"] = STATE_VERSION + rng.randint(1, 1_000)
        elif name == "array_top":
            doc = [doc]
        with pytest.raises(expected):
            load_state(json.dumps(doc))


# --- 5. migration: the REAL v1→v2 step + synthetic multi-step dispatch ------------


def _v0_doc() -> dict:
    """A fabricated pre-history save: v0 had no lifetime/prestige tracking."""
    return {
        "state_version": 0,
        "balances": {"cur-a": 42},
        "owned": {"gen-a": 3},
        "last_seen": 123,
        "upgrades": {},
    }


def _migrate_v0(doc: dict) -> dict:
    migrated = dict(doc)
    migrated["lifetime"] = dict(migrated["balances"])  # best-known backfill
    migrated["prestige"] = {}
    migrated["state_version"] = 1
    return migrated


def test_registry_carries_exactly_the_v1_migration():
    """Version policy: v2 shipped WITH its v1 migration in the same PR."""
    assert sorted(persistence._MIGRATIONS) == [1]
    assert STATE_VERSION == 2


def test_v1_document_migrates_to_v2_with_no_milestones():
    """The first REAL migration: a v1 save loads as v2 with an empty
    earned set — achievements did not exist before v2."""
    loaded = load_state(_dump_doc(_valid_v1_doc()))
    assert loaded == GameState(
        balances={"cur-a": 42},
        owned={"gen-a": 3},
        last_seen=1_700_000_000,
        upgrades={"up-a": 2},
        lifetime={"cur-a": 999},
        prestige={"meta": 1},
        milestones={},
    )
    # The migrated document is a first-class v2 citizen: it re-dumps
    # canonically and round-trips like any native save.
    assert load_state(dump_state(loaded)) == loaded


def test_canonical_v1_empty_literal_migrates_to_canonical_v2():
    assert load_state(CANONICAL_V1_EMPTY) == GameState()
    assert dump_state(load_state(CANONICAL_V1_EMPTY)) == CANONICAL_EMPTY


def test_v1_document_cannot_smuggle_a_milestones_field():
    """A v1 save carrying the v2-only field was never a valid v1 document;
    the migration refuses to bless it instead of silently wiping it."""
    with pytest.raises(FieldSetError):
        load_state(_dump_doc(_valid_v1_doc(milestones={"owned-1": 1})))


def test_v1_documents_with_other_unknown_fields_still_red():
    with pytest.raises(FieldSetError, match="surplus"):
        load_state(_dump_doc(_valid_v1_doc(surplus=1)))


def test_migrated_documents_still_face_v2_validation():
    bad = _valid_v1_doc()
    bad["balances"]["cur-a"] = -1
    with pytest.raises(NegativeValueError):
        load_state(_dump_doc(bad))


def test_synthetic_v0_migration_walks_the_full_chain(monkeypatch):
    """v0 → v1 (synthetic, in-test) → v2 (real): multi-step dispatch."""
    monkeypatch.setitem(persistence._MIGRATIONS, 0, _migrate_v0)
    loaded = load_state(json.dumps(_v0_doc()))
    assert loaded == GameState(
        balances={"cur-a": 42},
        owned={"gen-a": 3},
        last_seen=123,
        upgrades={},
        lifetime={"cur-a": 42},
        prestige={},
        milestones={},
    )
    assert load_state(dump_state(loaded)) == loaded


def test_migration_chain_stops_exactly_at_current_version(monkeypatch):
    monkeypatch.setattr(persistence, "STATE_VERSION", 3)
    monkeypatch.setitem(persistence._MIGRATIONS, 0, _migrate_v0)

    def _migrate_v2(doc: dict) -> dict:
        return {**doc, "state_version": 3}

    monkeypatch.setitem(persistence._MIGRATIONS, 2, _migrate_v2)
    # v0 walks 0 -> 1 -> 2 (real) -> 3; the chain stops exactly at STATE_VERSION.
    assert persistence._migrate(_v0_doc(), 0)["state_version"] == 3


def test_misbehaving_migrations_fail_loud(monkeypatch):
    monkeypatch.setitem(persistence._MIGRATIONS, 0, lambda doc: "not a document")
    with pytest.raises(MalformedSaveError):
        load_state(json.dumps(_v0_doc()))
    monkeypatch.setitem(
        persistence._MIGRATIONS, 0, lambda doc: {**doc, "state_version": 5}
    )
    with pytest.raises(UnknownVersionError):  # skipped versions are not a path
        load_state(json.dumps(_v0_doc()))
    monkeypatch.setitem(persistence._MIGRATIONS, 0, lambda doc: dict(doc))
    with pytest.raises(UnknownVersionError):  # forgot to bump: not v0+1
        load_state(json.dumps(_v0_doc()))


def test_unregistered_old_version_names_the_migratable_set(monkeypatch):
    monkeypatch.setitem(persistence._MIGRATIONS, 0, _migrate_v0)
    with pytest.raises(UnknownVersionError, match=r"\[0, 1\]"):
        load_state('{"state_version":-1}')


# --- 6. cross-module integration -------------------------------------------------

REPO_THEMES = REPO_ROOT / "themes"


def _play(theme, seed: int, save_load_at: int | None) -> list[GameState]:
    """A seeded playthrough; optionally serialize+load mid-run at one step."""
    rng = Random(seed)
    gens = theme.generator_specs()
    ups = theme.upgrade_specs()
    pr = theme.prestige_spec()
    prs = [pr] if pr is not None else []
    mss = theme.milestone_specs()
    state = GameState(owned={gens[0].spec_id: 1})
    trajectory = [state]
    for step in range(40):
        if step == save_load_at:
            state = load_state(dump_state(state))  # the persistence seam
        op = rng.choice(("tick", "offline", "buy", "prestige", "award"))
        if op == "tick":
            state = tick(state, gens, rng.randint(0, 100_000), ups, prs, mss)
        elif op == "offline":
            now = state.last_seen + rng.randint(-100, 100_000)
            state = apply_offline_progress(state, gens, now, ups, prs, mss)
        elif op == "buy" and ups:
            spec = rng.choice(ups)
            cost = upgrade_cost(spec, state.upgrades.get(spec.spec_id, 0))
            if state.balances.get(spec.cost_currency, 0) >= cost:
                state = purchase_upgrade(state, spec)
        elif op == "prestige" and prs and prestige_eligible(state, prs[0]):
            state = apply_prestige(state, prs[0])
        elif op == "award":
            state = award_milestones(state, mss)
        trajectory.append(state)
    return trajectory


@pytest.mark.parametrize("path", sorted(REPO_THEMES.glob("*.yaml")), ids=lambda p: p.stem)
def test_save_load_mid_playthrough_changes_nothing(path):
    """Serialize mid-run, load, keep ticking: the trajectory is identical."""
    theme = load_theme(path)
    for seed in (7, 42):
        uninterrupted = _play(theme, seed, save_load_at=None)
        for cut in (0, 13, 39):
            assert _play(theme, seed, save_load_at=cut) == uninterrupted


def test_every_trajectory_state_round_trips():
    theme = load_theme(REPO_THEMES / "egg-farm.yaml")
    for state in _play(theme, 20260711, save_load_at=None):
        assert load_state(dump_state(state)) == state
